In [28]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [30]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [31]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [32]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [33]:
df.shape

(569, 31)

In [34]:
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [35]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [36]:
X_train

array([[ 3.06767164e-01,  2.48911398e+00,  2.13542954e-01, ...,
        -7.45985769e-01,  5.39163880e-01, -1.20956843e+00],
       [ 2.86186353e-01,  1.32017934e-01,  3.66451421e-01, ...,
         1.48538965e+00, -9.99936825e-02, -7.22390424e-02],
       [ 3.86136723e+00,  6.13829151e-01,  3.85054965e+00, ...,
         2.36263021e+00, -6.47519121e-02, -1.55793449e-01],
       ...,
       [-3.63579249e-01,  4.95738167e-01, -3.86164908e-01, ...,
        -8.95101354e-01, -6.54250616e-01, -1.17864146e-01],
       [-1.35880846e+00,  4.10712658e-01, -1.34535674e+00, ...,
        -7.54865342e-01, -2.95101418e-02,  4.64817898e-01],
       [ 1.22408331e+00,  1.67445230e-01,  1.18849416e+00, ...,
         1.20522382e+00,  2.66841109e-01,  1.42076318e-03]],
      shape=(455, 30))

In [37]:
y_train

414    M
94     M
180    M
160    B
193    M
      ..
236    M
154    B
407    B
66     B
6      M
Name: diagnosis, Length: 455, dtype: str

In [38]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [39]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [75]:
#  Numpy array to Pytorch Tensors
import torch

X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

In [76]:
X_train_tensor

tensor([[ 3.0677e-01,  2.4891e+00,  2.1354e-01,  ..., -7.4599e-01,
          5.3916e-01, -1.2096e+00],
        [ 2.8619e-01,  1.3202e-01,  3.6645e-01,  ...,  1.4854e+00,
         -9.9994e-02, -7.2239e-02],
        [ 3.8614e+00,  6.1383e-01,  3.8505e+00,  ...,  2.3626e+00,
         -6.4752e-02, -1.5579e-01],
        ...,
        [-3.6358e-01,  4.9574e-01, -3.8616e-01,  ..., -8.9510e-01,
         -6.5425e-01, -1.1786e-01],
        [-1.3588e+00,  4.1071e-01, -1.3454e+00,  ..., -7.5487e-01,
         -2.9510e-02,  4.6482e-01],
        [ 1.2241e+00,  1.6745e-01,  1.1885e+00,  ...,  1.2052e+00,
          2.6684e-01,  1.4208e-03]])

In [77]:
y_train_tensor.shape

torch.Size([455, 1])

In [78]:
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [79]:
learning_rate = 0.1
epochs = 25

In [80]:
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
# define the loss function
optimiser = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [85]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Define loops
for epoch in range(epochs):
    #forward pass
    y_pred = model(X_train_tensor)
    # print(y_pred)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor)
    # print(f"Epoch:{epoch}, Loss:{loss.item()}")

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    #print loss in each epoch
    print(f"Epoch:{epoch+1}, Loss:{loss.item()}")

Epoch:1, Loss:0.8329985737800598
Epoch:2, Loss:0.6012358069419861
Epoch:3, Loss:0.48465263843536377
Epoch:4, Loss:0.4159992039203644
Epoch:5, Loss:0.36987727880477905
Epoch:6, Loss:0.33635464310646057
Epoch:7, Loss:0.31068482995033264
Epoch:8, Loss:0.29027971625328064
Epoch:9, Loss:0.27359575033187866
Epoch:10, Loss:0.2596500813961029
Epoch:11, Loss:0.24778468906879425
Epoch:12, Loss:0.23754112422466278
Epoch:13, Loss:0.22858929634094238
Epoch:14, Loss:0.22068510949611664
Epoch:15, Loss:0.21364380419254303
Epoch:16, Loss:0.20732277631759644
Epoch:17, Loss:0.2016100138425827
Epoch:18, Loss:0.19641636312007904
Epoch:19, Loss:0.19166961312294006
Epoch:20, Loss:0.1873108297586441
Epoch:21, Loss:0.18329133093357086
Epoch:22, Loss:0.1795704960823059
Epoch:23, Loss:0.17611409723758698
Epoch:24, Loss:0.17289315164089203
Epoch:25, Loss:0.16988283395767212

In [86]:
model.linear.bias

Parameter containing:
tensor([-0.0840], requires_grad=True)

In [87]:
model.linear.weight

Parameter containing:
tensor([[ 0.1873,  0.2225,  0.4365,  0.2627,  0.2204, -0.0197,  0.2719,  0.1703,
         -0.0671,  0.0395,  0.1711,  0.0718,  0.2641,  0.0666, -0.0473,  0.0992,
         -0.1094,  0.0213, -0.0587,  0.1040,  0.2748,  0.3005,  0.1748,  0.4281,
          0.3091,  0.1864,  0.0404,  0.1587,  0.1737,  0.0777]],
       requires_grad=True)

In [88]:
# model evalution
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred== y_test_tensor).float().mean()
print(f'Accuracy:{accuracy.item()}')
# print(y_pred)

Accuracy:0.9561403393745422