In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

In [7]:
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [8]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [9]:
X_train

array([[ 2.35753271e-01, -8.92799448e-01,  2.14332853e-01, ...,
         3.57363021e-01,  1.14815273e-01,  1.34654466e-03],
       [-9.90961243e-01, -2.46034306e-01, -1.01652467e+00, ...,
        -1.40909422e+00, -3.17236167e-01, -9.50147378e-01],
       [-8.49736773e-01, -1.28649885e-01, -7.56127776e-01, ...,
         2.10580142e+00,  2.14799852e+00,  3.31811626e+00],
       ...,
       [-6.61437479e-01, -2.87464102e-01, -6.87813778e-01, ...,
        -6.55051526e-01, -1.53884044e+00, -8.45401122e-01],
       [-4.75907293e-01, -5.49852807e-01, -5.43148839e-01, ...,
        -1.31594597e+00, -1.66930303e+00, -1.42062777e+00],
       [-3.65143003e-01,  6.76929473e-01, -2.75518703e-01, ...,
         1.27052124e+00,  8.82341949e-01,  2.38183688e+00]],
      shape=(455, 30))

In [10]:
y_train

227    B
443    B
379    M
10     M
201    M
      ..
533    M
550    B
297    M
319    B
229    M
Name: diagnosis, Length: 455, dtype: str

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1])

In [13]:
#  Numpy array to Pytorch Tensors
import torch

X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor

tensor([[ 2.3575e-01, -8.9280e-01,  2.1433e-01,  ...,  3.5736e-01,
          1.1482e-01,  1.3465e-03],
        [-9.9096e-01, -2.4603e-01, -1.0165e+00,  ..., -1.4091e+00,
         -3.1724e-01, -9.5015e-01],
        [-8.4974e-01, -1.2865e-01, -7.5613e-01,  ...,  2.1058e+00,
          2.1480e+00,  3.3181e+00],
        ...,
        [-6.6144e-01, -2.8746e-01, -6.8781e-01,  ..., -6.5505e-01,
         -1.5388e+00, -8.4540e-01],
        [-4.7591e-01, -5.4985e-01, -5.4315e-01,  ..., -1.3159e+00,
         -1.6693e+00, -1.4206e+00],
        [-3.6514e-01,  6.7693e-01, -2.7552e-01,  ...,  1.2705e+00,
          8.8234e-01,  2.3818e+00]])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [21]:
# Defining the model
class MySimpleNN():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float32, requires_grad=True)
        self.bias = torch.rand(1, dtype=torch.float32, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
        
class MySimpleNN:

    def __init__(self, X):
        self.weights = torch.rand(
            X.shape[1], 1,
            dtype=torch.float32,
            requires_grad=True
        )

        self.bias = torch.zeros(
            1,
            dtype=torch.float32,
            requires_grad=True
        )

    def forward(self, X):
        return torch.sigmoid(X @ self.weights + self.bias)

    def binary_cross_entropy_loss(self, y_pred, y_true):
        epsilon = 1e-7

        y_pred = torch.clamp(
            y_pred,
            epsilon,
            1 - epsilon
        )

        loss = -torch.mean(
            y_true * torch.log(y_pred)
            + (1 - y_true) * torch.log(1 - y_pred)
        )

        return loss

In [18]:
learning_rate = 0.1
epochs = 25

In [28]:
# create model
model = MySimpleNN(X_train_tensor)

# Define loops
for epoch in range(epochs):
    #forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)

    # loss calculate
    loss = model.binary_cross_entropy_loss(y_pred, y_train_tensor)
    # print(f"Epoch:{epoch}, Loss:{loss.item()}")

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss in each epoch
    print(f"Epoch:{epoch+1}, Loss:{loss.item()}")

Epoch:1, Loss:3.4962384700775146
Epoch:2, Loss:3.3690125942230225
Epoch:3, Loss:3.23915433883667
Epoch:4, Loss:3.1041738986968994
Epoch:5, Loss:2.9651379585266113
Epoch:6, Loss:2.8169922828674316
Epoch:7, Loss:2.6634490489959717
Epoch:8, Loss:2.5035858154296875
Epoch:9, Loss:2.3375821113586426
Epoch:10, Loss:2.1721651554107666
Epoch:11, Loss:2.0116493701934814
Epoch:12, Loss:1.855820894241333
Epoch:13, Loss:1.7064288854599
Epoch:14, Loss:1.5604500770568848
Epoch:15, Loss:1.4238719940185547
Epoch:16, Loss:1.3002077341079712
Epoch:17, Loss:1.1922900676727295
Epoch:18, Loss:1.1003047227859497
Epoch:19, Loss:1.0244674682617188
Epoch:20, Loss:0.9640272259712219
Epoch:21, Loss:0.917391300201416
Epoch:22, Loss:0.882236897945404
Epoch:23, Loss:0.8559459447860718
Epoch:24, Loss:0.8360774517059326
Epoch:25, Loss:0.8206610083580017

In [29]:
model.bias

tensor([-0.1270], requires_grad=True)

In [30]:
model.weights

tensor([[ 0.4329],
        [ 0.0224],
        [-0.1861],
        [-0.0852],
        [ 0.4363],
        [-0.0706],
        [ 0.1054],
        [-0.3960],
        [-0.0810],
        [ 0.5802],
        [ 0.1025],
        [ 0.3025],
        [ 0.0119],
        [-0.0222],
        [ 0.0854],
        [-0.2292],
        [-0.2569],
        [ 0.2335],
        [ 0.4661],
        [-0.2882],
        [ 0.3839],
        [ 0.5047],
        [-0.2381],
        [ 0.3112],
        [-0.1332],
        [-0.3000],
        [ 0.2903],
        [-0.4981],
        [ 0.2742],
        [ 0.0294]], requires_grad=True)

In [ ]:
# model evalution
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred== y_test_tensor).float().mean()
print(f'Accuracy:{accuracy.item()}')
# print(y_pred)

Accuracy:0.5360110998153687
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]])

Accuracy:0.5360110998153687